# Generated by Django 3.1.1 on 2020-09-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagonka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('depth', models.CharField(max_length=20, verbose_name='Толщина')),
                ('width', models.CharField(max_length=20, verbose_name='Общая ширина')),
                ('working_width', models.CharField(max_length=20, verbose_name='Рабочая ширина')),
                ('length', models.CharField(max_length=20, verbose_name='Длина')),
                ('country', models.CharField(max_length=20, verbose_name='Страна производства')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Terrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('depth', models.CharField(max_length=20, verbose_name='Толщина')),
                ('width', models.CharField(max_length=20, verbose_name='Общая ширина')),
                ('working_width', models.CharField(max_length=20, verbose_name='Рабочая ширина')),
                ('length', models.CharField(max_length=20, verbose_name='Длина')),
                ('country', models.CharField(max_length=20, verbose_name='Страна производства')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
