# Generated by Django 3.1.1 on 2020-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200922_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vagonka',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
