# Generated by Django 3.1.1 on 2020-09-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='stairs',
            options={'verbose_name': 'Лестничные элементы'},
        ),
        migrations.AlterModelOptions(
            name='terrace',
            options={'verbose_name': 'Террасная доска'},
        ),
        migrations.AlterModelOptions(
            name='vagonka',
            options={'verbose_name': 'Вагонка'},
        ),
    ]
