# Generated by Django 3.1.1 on 2020-09-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200929_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='stairs',
            options={'verbose_name': 'Лестничные элементы', 'verbose_name_plural': 'Лестничные элементы'},
        ),
        migrations.AlterModelOptions(
            name='terrace',
            options={'verbose_name': 'Террасная доска', 'verbose_name_plural': 'Террасная доска'},
        ),
        migrations.AlterModelOptions(
            name='vagonka',
            options={'verbose_name': 'Вагонка', 'verbose_name_plural': 'Вагонка'},
        ),
    ]
